### ISSUE TITLE
ぷかぷか丸から先に進まない

### ISSUE THREAD

**Issue by shokai** [geta6/teitoku#4]
どうもiframeの中をいじってしまうとswfがぷかぷか丸から進まないように使用変更されたんじゃないかと思う

`app:start`しなかったらぷかぷか丸から先に進めるので
で、embedタグを作るかわりに既存のiframeなどをcssで無理やり左上に移動させてみたらなんとかなりそうな雰囲気だった。でもちょっと左にすきまあいてよくわからなかったので眠くなった

**Comment by geta6** [comment]
うす

**Comment by shokai** [comment]
そんな事なかった

``` coffee
 $win.on 'app:run', (event, embed) ->
   console.debug 'app:run'
+  location.href = ($ embed).attr 'src'
+  return
```

こうしてみたら普通にswf表示できる（もちろんキャプチャ等はできない）ので
swfobjectがおかしいのでは疑惑

**Comment by geta6** [comment]
ありがとうございました
