### ISSUE TITLE
cmd+q, cmd+wなどの無効化復活希望

### ISSUE THREAD

**Issue by shokai** [geta6/teitoku#6]
2.xまであった、「ウィンドウを閉じるショートカットキー」を無効にしていた機能
復活希望です

あれがあると間違えて閉じてしまう事がなくて良いです

**Comment by geta6** [comment]
着任後、有効になっているはずですがどうでしょう(｡ŏ﹏ŏ｡)

**Comment by shokai** [comment]
まじで、試す

**Comment by shokai** [comment]
なってました！
やったぜ！

![LGTM](http://www.lgtm.in/p/2Do1)
