### ISSUE TITLE
iframeにフォーカスを取られてしまい、キーイベントが受け付けられない

### ISSUE THREAD

**Issue by shokai** [geta6/teitoku#7]
やはり https://github.com/geta6/teitoku/commit/edd27b29a12e00c49b55bd8d0c19954bc73dfcf6#diff-5213ac8fbf5fc6caa4a679def1b21649R114 の

``` coffee
+  $win.on 'blur', ->
 +    $win.focus()
```

on 'blur'だと動いていないようです

他のアプリをアクティブにする→teitokuに戻ってくる→hやcを押しても効かない！

**Comment by shokai** [comment]
たぶんこういうのは
https://github.com/rogerwang/node-webkit/pull/1735
グローバルキーフックを使うべきなんだろうけどまだmergeされてない

**Comment by geta6** [comment]
fixed in 49064e0

**Comment by geta6** [comment]
globalとiframe、二つのwindowが存在しているのが原因なので、イベント処理を外部化した

**Comment by shokai** [comment]
なるほどそっちが原因か
