### ISSUE TITLE
iframe化した副作用を調査する等

### ISSUE THREAD

**Issue by shokai** [geta6/teitoku#8]
embedタグやめてiframeにしたので
- [x] src/lib/swfobject.js はいらない
- [x] src/lib/expressInstall.swf もいらない？
- [x] flashが入ってない環境で、flashプレイヤーインストールの案内が出るか確認する

こんなものでしょうか

**Comment by geta6** [comment]
やったほうがよさそうですね、あざす！

**Comment by shokai** [comment]
- swfobject.jsなくても動いたので、削除してok
- flashが無い環境で実行してみた
  - package.jsonでplugin: falseにして起動した、たぶんこれでflashなしになるよね？
  - `app:run`はtriggerされるけど、コールバックの第二引数embedがundefinedでtriggerされる

もしflashなしの時の案内を表示するのにswfobject.js使ったほうが楽なら、案内のためだけだけに使えばいいと思う

**Comment by geta6** [comment]
> embedがundefinedでtrigger

了解す！

**Comment by geta6** [comment]
0.3.2で解決しました
